/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelo.Noticia;

/**
 *
 * @author dam
 */
public class PanelConsulta extends javax.swing.JPanel {

    Empresa empresa;
    int posLogueado;
    DefaultTableModel modelo;

    /**
     * Creates new form PanelConsulta
     */
    public PanelConsulta(Empresa empresa, int posLogueado) {
        initComponents();
        this.empresa = empresa;
        this.posLogueado = posLogueado;
        configurarCuadricula();
        mostrarNoticias();
    }

    private void configurarCuadricula() {
        modelo = new DefaultTableModel();
        String [] titulos={"Codgio", "Titulo", "Fecha", "Categoria"};
        modelo.setColumnIdentifiers(titulos);
        tblNoticias.setModel(modelo);
    }
    
    private void mostrarNoticias(){
        ArrayList<Noticia> noticias=empresa.getNoticias();
        for(Noticia n:noticias){
            Vector v=new Vector();
            v.add(n.getCodigo());
            v.add(n.getTitulo());
            v.add(n.getFecha());
            v.add(n.getCategoria());
            modelo.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoticias = new javax.swing.JTable();

        tblNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNoticias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNoticias;
    // End of variables declaration//GEN-END:variables
}
