/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Empresa;
import java.awt.BorderLayout;

/**
 *
 * @author dam
 */
public class VtnOpciones extends javax.swing.JFrame {

    Empresa empresa;
    int posLogueado;
    PanelAlta panelAlta;
    PanelConsulta panelConsulta;
    

    /**
     * Creates new form VtnOpciones
     */
    public VtnOpciones() {
        initComponents();
    }

    public VtnOpciones(Empresa empresa, int pos) {
        initComponents();
        this.empresa = empresa;
        this.posLogueado = pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();
        mnuFinalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("NOTICIAS");

        mnuAlta.setText("ALTA NOTICIAS");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlta);

        mnuConsulta.setText("CONSULTA");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("SALIR");

        mnuDesconectar.setText("DESCONECTAR");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDesconectar);

        mnuFinalizar.setText("FIN APLICACION");
        mnuFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinalizarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuFinalizar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinalizarActionPerformed
        dispose();
        pack();
        System.exit(0);
    }//GEN-LAST:event_mnuFinalizarActionPerformed

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        dispose();
        new VtnLogin(empresa).setVisible(true);
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
        eliminarPaneles();
        panelAlta = new PanelAlta(empresa, posLogueado);
        getContentPane().add(panelAlta);
        pack();
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        eliminarPaneles();
        panelConsulta= new PanelConsulta(empresa,posLogueado);
        getContentPane().add(panelConsulta,BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void eliminarPaneles() {
        try {
            remove(panelAlta);
        } catch (Exception ex) {}
               try {
            remove(panelConsulta);
        } catch (Exception ex) {}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuFinalizar;
    // End of variables declaration//GEN-END:variables
}
